[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

# Force HTTPS and redirect non-www to www
[[redirects]]
  from = "http://mainepestpros.com/*"
  to = "https://www.mainepestpros.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.mainepestpros.com/*"
  to = "https://www.mainepestpros.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://mainepestpros.com/*"
  to = "https://www.mainepestpros.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[plugins]]
  package = "netlify-plugin-minify-html"